name: news_apps_bloc
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  flutter_animate: ^4.5.2
  http: ^1.3.0
  google_fonts: ^6.2.1
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  timeago: 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
